export const actionTypes = {
	LOG_OUT: 'LOG_OUT',
	REGISTER_FAILED: 'REGISTER_FAILED',
	VERIFY_FAILED: 'VERIFY_FAILED',
	REGISTER_SUCCES: 'REGISTER_SUCCES',
	VERIFY_SUCCESS: 'VERIFY_SUCCESS',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOGIN_ADMIN_SUCCESS: 'LOGIN_ADMIN_SUCCESS',
	LOGIN_ADMIN_FAIL: 'LOGIN_ADMIN_FAIL',
	GET_PARTIES: 'GET_PARTIES',
	GET_PARTIES_BY_CATEGORY: 'GET_PARTIES_BY_CATEGORY',
	GET_USER: 'GET_USER',
};
